import { COUNTRIES, countryById, createWorldState } from './world-data.js';
import { COUNTRY_GYMS, SUBJECTS, SUBJECT_TRAINER_TITLES, createSubjectState, subjectById } from './subject-data.js';

const PROFILE_KEY='ascend_project_kayla_v4';
const load=()=>{try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')}catch{return {}}};
const save=(p)=>localStorage.setItem(PROFILE_KEY,JSON.stringify(p));

function ensure(p){p.world=createWorldState(p.world||{});p.subjects=createSubjectState(p.subjects||{});return p;}
function levelFor(p){return Math.max(1,Math.min(12,Number(p.schoolYear||5)));}
function weakestSubject(p){return [...SUBJECTS].sort((a,b)=>(p.subjects.mastery[a.id]||0)-(p.subjects.mastery[b.id]||0))[0];}

const trainers=['Ari','Bex','Cato','Demi','Eli','Fia','Gus','Hana','Ivo','Juno','Kiri','Lio','Mina','Nox','Ola','Pax','Rin','Sol','Tala','Uma'];
function makeTrainer(country,index,p){const subject=index%3===0?weakestSubject(p):SUBJECTS[(index+COUNTRIES.indexOf(country))%SUBJECTS.length];const title=SUBJECT_TRAINER_TITLES[subject.id][index%4];return {id:`${country.id}-trainer-${index}`,name:trainers[(index+COUNTRIES.indexOf(country)*4)%trainers.length],title,subject:subject.id,level:Math.max(1,levelFor(p)-1+(index%3)),location:country.locations[index%country.locations.length]};}

function question(subjectId,year){
  const r=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
  const choices=(correct,wrong)=>[correct,...wrong].sort(()=>Math.random()-.5);
  if(subjectId==='mathematics'){
    if(year<=4){const a=r(2,12),b=r(2,12),c=a*b;return {prompt:`${a} × ${b} = ?`,answer:String(c),options:choices(String(c),[String(c+a),String(Math.max(0,c-b)),String(a+b)]),explain:`${a} groups of ${b} make ${c}.`};}
    if(year<=8){const percent=[10,20,25,50][r(0,3)],base=[40,60,80,100,200][r(0,4)],c=percent/100*base;return {prompt:`What is ${percent}% of ${base}?`,answer:String(c),options:choices(String(c),[String(c+10),String(Math.max(0,c-5)),String(base-percent)]),explain:`${percent}% means ${percent} out of 100.`};}
    const x=r(2,12),m=r(2,6),b=r(1,9),total=m*x+b;return {prompt:`Solve ${m}x + ${b} = ${total}`,answer:String(x),options:choices(String(x),[String(x+1),String(x-1),String(total-m)]),explain:`Subtract ${b}, then divide by ${m}.`};
  }
  if(subjectId==='english'){
    const bank=year<=6?[{p:'Which sentence uses an adjective?',a:'The bright bird sang.',w:['Birds sing.','Run quickly.','She smiled.']},{p:'Which word is spelled correctly?',a:'because',w:['becaus','becose','beacause']}]:[{p:'Which sentence contains a metaphor?',a:'The classroom was a zoo.',w:['The classroom was noisy.','The classroom felt like a zoo.','Animals live in a zoo.']},{p:'Which is the strongest topic sentence?',a:'Regular reading improves vocabulary, comprehension and confidence.',w:['Reading is a thing.','Books exist in libraries.','I read sometimes.']}];const q=bank[r(0,bank.length-1)];return {prompt:q.p,answer:q.a,options:choices(q.a,q.w),explain:'Read for meaning, grammar and the author’s purpose.'};
  }
  if(subjectId==='science'){
    const qs=year<=6?[{p:'What do plants need to make food?',a:'Light, water and carbon dioxide',w:['Only soil','Only oxygen','Heat and salt']},{p:'Which is a solid?',a:'Ice',w:['Steam','Rain','Air']}]:[{p:'What happens to particles when a substance is heated?',a:'They move faster',w:['They disappear','They stop moving','They become heavier']},{p:'Which organelle controls a cell?',a:'Nucleus',w:['Cell wall','Vacuole','Cytoplasm']}];const q=qs[r(0,qs.length-1)];return {prompt:q.p,answer:q.a,options:choices(q.a,q.w),explain:'Use observable evidence and scientific models.'};
  }
  if(subjectId==='humanities')return {prompt:'Which source is primary evidence?',answer:'A diary written during the event',options:choices('A diary written during the event',['A modern textbook','A recent documentary','A summary website']),explain:'Primary sources were created at the time or by direct participants.'};
  if(subjectId==='technologies')return {prompt:'What should an algorithm contain?',answer:'Clear ordered steps',options:choices('Clear ordered steps',['Only pictures','Random actions','A final answer with no method']),explain:'Algorithms describe a repeatable sequence of actions.'};
  if(subjectId==='health')return {prompt:'Which choice best supports wellbeing?',answer:'Sleep, movement, food and trusted support',options:choices('Sleep, movement, food and trusted support',['Skipping sleep','Ignoring unsafe situations','Never asking for help']),explain:'Wellbeing is supported by balanced habits and safe relationships.'};
  if(subjectId==='arts')return {prompt:'What creates contrast in an artwork?',answer:'Strong differences between elements',options:choices('Strong differences between elements',['Making everything identical','Removing all shapes','Using one repeated sound only']),explain:'Contrast uses differences in colour, size, sound, shape or movement.'};
  return {prompt:'What is the respectful first step when learning another language?',answer:'Listen carefully and practise respectfully',options:choices('Listen carefully and practise respectfully',['Mock unfamiliar sounds','Assume every culture is the same','Avoid speaking']),explain:'Language learning involves listening, practice and cultural respect.'};
}

const css=document.createElement('style');css.textContent=`
#ascend-adventure-button{position:fixed;right:max(14px,env(safe-area-inset-right));top:82px;z-index:120100;border:4px solid #fff;border-radius:18px;padding:12px 16px;background:#ffca57;color:#17324d;font:900 14px Nunito,sans-serif;box-shadow:0 8px 24px #17324d33;cursor:pointer}
#ascend-adventure{position:fixed;inset:0;z-index:140000;display:none;overflow:auto;padding:calc(16px + env(safe-area-inset-top)) 16px calc(22px + env(safe-area-inset-bottom));background:linear-gradient(180deg,#8ee7ff,#dff7d8 58%,#7fd778);font-family:Nunito,sans-serif;color:#17324d}#ascend-adventure.open{display:block}.al-shell{max-width:1120px;margin:auto}.al-top{display:flex;justify-content:space-between;gap:12px;align-items:center}.al-close{border:0;border-radius:14px;padding:11px 15px;background:#17324d;color:#fff;font-weight:900}.al-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:16px}.al-card{background:#fff8dff5;border:5px solid #fff;border-radius:24px;padding:17px;box-shadow:0 12px 28px #17324d22}.al-country{display:flex;gap:8px;flex-wrap:wrap}.al-chip,.al-action{border:3px solid #fff;border-radius:14px;padding:10px 13px;background:#73d8bd;font-weight:900;cursor:pointer}.al-chip.active{outline:4px solid #ffca57}.al-trainer,.al-gym{background:#fff;border-radius:16px;padding:13px;margin:9px 0}.al-action.gym{background:#8d72e8;color:#fff}.al-action.roam{background:#ffca57}.al-bar{height:15px;background:#ddd;border-radius:99px;overflow:hidden}.al-bar span{display:block;height:100%;background:#73d8bd}.al-battle{position:fixed;inset:0;z-index:150000;display:grid;place-items:center;padding:16px;background:#17324dcc}.al-battle-card{width:min(760px,96vw);background:#fff8df;border:7px solid #fff;border-radius:28px;padding:22px;text-align:center}.al-options{display:grid;grid-template-columns:1fr 1fr;gap:12px}.al-option{min-height:58px;border:4px solid #fff;border-radius:15px;background:#d9d0ff;font:800 18px Nunito,sans-serif;color:#17324d}.al-option:active{transform:scale(.98)}.al-result{min-height:54px;margin-top:12px;font-weight:800}@media(max-width:760px){#ascend-adventure-button{top:auto;bottom:calc(150px + env(safe-area-inset-bottom));right:12px}.al-grid{grid-template-columns:1fr}.al-options{grid-template-columns:1fr}.al-card{padding:13px}.al-battle-card{padding:16px}}
`;document.head.appendChild(css);

const button=document.createElement('button');button.id='ascend-adventure-button';button.textContent='⚔️ ADVENTURE';document.body.appendChild(button);
const app=document.createElement('section');app.id='ascend-adventure';app.innerHTML=`<div class="al-shell"><div class="al-top"><div><h1 style="margin:0;color:#6b4cc5;font-family:'Baloo 2'">Living World Adventures</h1><div>Roaming trainers, subject gyms, wild encounters and country life.</div></div><button class="al-close">BACK</button></div><div class="al-country"></div><div class="al-grid"></div></div>`;document.body.appendChild(app);
let selected='verdara';

function render(){const p=ensure(load());save(p);selected=p.world.currentCountry||selected;const country=countryById(selected);const nav=app.querySelector('.al-country');nav.innerHTML='';COUNTRIES.forEach(c=>{const b=document.createElement('button');b.className=`al-chip ${c.id===selected?'active':''}`;b.textContent=`${c.icon} ${c.name}`;b.disabled=!p.world.progress[c.id].unlocked;b.onclick=()=>{selected=c.id;p.world.currentCountry=c.id;save(p);render()};nav.appendChild(b)});
 const trainersHere=Array.from({length:5},(_,i)=>makeTrainer(country,i,p));const gyms=COUNTRY_GYMS[country.id]||[];const weak=weakestSubject(p);app.querySelector('.al-grid').innerHTML=`<div><div class="al-card"><h2>${country.icon} ${country.name} feels alive</h2><p>Current focus: <b>${weak.icon} ${weak.name}</b>. Citizens travel between ${country.locations.join(', ')}. Traders, students, researchers and monster keepers appear throughout the day.</p><button class="al-action roam" data-roam>ROAM THE COUNTRY</button><div class="al-result" data-world-result>Walk the roads to trigger trainers, cultural events, wild monsters and local requests.</div></div><div class="al-card"><h3>Roaming Subject Trainers</h3>${trainersHere.map(t=>`<div class="al-trainer"><b>${t.name}, ${t.title}</b><br>${subjectById(t.subject).icon} ${subjectById(t.subject).name} · Level ${t.level}<br><small>${t.location}</small><br><button class="al-action" data-trainer="${t.id}">BATTLE</button></div>`).join('')}</div></div><div><div class="al-card"><h3>Country Subject Gyms</h3>${gyms.map((g,i)=>{const s=subjectById(g.subject);const cleared=p.subjects.badges[g.subject].includes(`${country.id}-${i}`);return `<div class="al-gym"><b>${s.icon} ${g.name}</b><br>Leader: ${g.leader}<br><small>${g.focus}</small><br>${cleared?'🏅 Badge earned':`<button class="al-action gym" data-gym="${i}">CHALLENGE GYM</button>`}</div>`}).join('')}</div><div class="al-card"><h3>School Mastery</h3>${SUBJECTS.map(s=>`<div style="margin:9px 0"><b>${s.icon} ${s.name}</b> ${Math.round((p.subjects.mastery[s.id]||0)*100)}%<div class="al-bar"><span style="width:${(p.subjects.mastery[s.id]||0)*100}%"></span></div></div>`).join('')}<p>Gyms go deeper than roaming battles. They test several domains and award permanent subject badges.</p></div></div>`;
 app.querySelector('[data-roam]').onclick=()=>roam(p,country,app.querySelector('[data-world-result]'));app.querySelectorAll('[data-trainer]').forEach((b,i)=>b.onclick=()=>startBattle(p,{type:'trainer',subject:trainersHere[i].subject,rounds:3,name:`${trainersHere[i].name}, ${trainersHere[i].title}`,year:trainersHere[i].level}));app.querySelectorAll('[data-gym]').forEach(b=>{const i=Number(b.dataset.gym),g=gyms[i];b.onclick=()=>startBattle(p,{type:'gym',subject:g.subject,rounds:6,name:`Gym Leader ${g.leader}`,year:levelFor(p),badge:`${country.id}-${i}`})});}

function roam(p,country,out){const events=[()=>{const t=makeTrainer(country,Math.floor(Math.random()*5),p);out.textContent=`${t.name}, ${t.title}, challenges you to a ${subjectById(t.subject).name} battle at ${t.location}.`;},()=>{const npc=country.npcs[Math.floor(Math.random()*country.npcs.length)];out.textContent=`${npc.name} needs help with ${npc.teaches}. A local mission has appeared.`;p.xp=(p.xp||0)+8;save(p);},()=>{out.textContent=`A wild monster trail crosses the road near ${country.locations[Math.floor(Math.random()*country.locations.length)]}. Open WORLD to track it safely.`;},()=>{out.textContent=`A market, festival or school gathering is active. You learn about ${country.culture.learning} and gain +10 XP.`;p.xp=(p.xp||0)+10;save(p);}];events[Math.floor(Math.random()*events.length)]();}

function startBattle(p,config){let round=0,correct=0;const modal=document.createElement('div');modal.className='al-battle';document.body.appendChild(modal);const next=()=>{if(round>=config.rounds)return finish();const q=question(config.subject,config.year);const s=subjectById(config.subject);modal.innerHTML=`<div class="al-battle-card"><h2>${config.type==='gym'?'GYM BATTLE':'TRAINER BATTLE'} · ${round+1}/${config.rounds}</h2><h3 style="color:${s.colour}">${s.icon} ${s.name}</h3><p><b>${config.name}</b></p><div style="font-size:24px;margin:18px">${q.prompt}</div><div class="al-options"></div><div class="al-result">Choose your move. Correct understanding powers your monster’s ability.</div><button class="al-action" data-quit>LEAVE BATTLE</button></div>`;const opts=modal.querySelector('.al-options'),result=modal.querySelector('.al-result');q.options.forEach(opt=>{const b=document.createElement('button');b.className='al-option';b.textContent=opt;b.onclick=()=>{const ok=String(opt)===q.answer;if(!ok){result.textContent=`Not yet. ${q.explain}`;b.disabled=true;p.subjects.mastery[config.subject]=Math.max(.05,p.subjects.mastery[config.subject]-.01);save(p);return;}correct++;p.subjects.mastery[config.subject]=Math.min(1,p.subjects.mastery[config.subject]+(config.type==='gym'?.045:.025));result.textContent=`Power move! ${q.explain}`;modal.querySelectorAll('.al-option').forEach(x=>x.disabled=true);setTimeout(()=>{round++;next()},650);save(p)};opts.appendChild(b)});modal.querySelector('[data-quit]').onclick=()=>modal.remove();};
 const finish=()=>{const win=correct>=Math.ceil(config.rounds*.6);if(win){p.subjects.battleStreak++;p.subjects.trainersDefeated+=(config.type==='trainer'?1:0);p.subjects.gymsCleared+=(config.type==='gym'?1:0);p.xp=(p.xp||0)+(config.type==='gym'?120:35);p.coins=(p.coins||0)+(config.type==='gym'?70:18);if(config.badge&&!p.subjects.badges[config.subject].includes(config.badge))p.subjects.badges[config.subject].push(config.badge);}else p.subjects.battleStreak=0;save(p);modal.innerHTML=`<div class="al-battle-card"><h2>${win?'VICTORY!':'TRAINING COMPLETE'}</h2><p>${correct}/${config.rounds} correct</p><p>${win?(config.type==='gym'?'Subject badge earned. Your monster gained major bond XP.':'Trainer defeated. Your monster gained bond XP.'):'You keep what you learned and can challenge again.'}</p><button class="al-action gym" data-done>RETURN TO WORLD</button></div>`;modal.querySelector('[data-done]').onclick=()=>{modal.remove();render()};};next();}

button.onclick=()=>{app.classList.add('open');render()};app.querySelector('.al-close').onclick=()=>app.classList.remove('open');
window.addEventListener('keydown',e=>{if(e.key==='Escape')app.classList.remove('open')});
