const KEY='ascend_project_kayla_v4';
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
const save=p=>localStorage.setItem(KEY,JSON.stringify(p));

const css=document.createElement('style');css.textContent=`
#ao3{position:fixed;inset:0;z-index:400000;display:none;background:linear-gradient(#8ee7ff,#dff8de 62%,#78d36f);font-family:Nunito,Arial;color:#17324d;overflow:hidden}#ao3.open{display:flex;flex-direction:column}body.ao3-open>#app{visibility:hidden}
.ao3-top{flex:0 0 auto;padding:calc(10px + env(safe-area-inset-top)) 14px 8px}.ao3-dots{display:flex;gap:7px;max-width:900px;margin:auto}.ao3-dot{height:9px;flex:1;border-radius:20px;background:#ffffff88}.ao3-dot.on{background:#6b4cc5}
.ao3-scroll{flex:1;overflow:auto;-webkit-overflow-scrolling:touch;padding:8px 14px 120px}.ao3-card{width:min(920px,100%);margin:auto;background:#fff8df;border:6px solid #fff;border-radius:28px;box-shadow:0 18px 50px #17324d2b;padding:18px;display:grid;grid-template-columns:minmax(260px,.9fr) minmax(300px,1.1fr);gap:18px}.ao3-preview{min-height:380px;border-radius:24px;background:linear-gradient(#c7f5ff,#e5f9dc 65%,#7fd574);display:grid;place-items:center;position:relative;overflow:hidden}.ao3-copy h1{font:800 52px 'Baloo 2',Arial;margin:0;color:#6b4cc5}.ao3-copy h2{font:800 29px 'Baloo 2',Arial;margin:0 0 10px}.ao3-copy p{font-size:18px;line-height:1.45}.ao3-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px;margin:10px 0}.ao3-opt{border:3px solid #fff;border-radius:15px;padding:11px;background:#edf7ff;font:900 15px Nunito;color:#17324d}.ao3-opt.sel{outline:4px solid #ffca57;background:#fff0ae}.ao3-colours{display:flex;flex-wrap:wrap;gap:9px;margin:9px 0}.ao3-colour{width:42px;height:42px;border-radius:50%;border:4px solid #fff;box-shadow:0 3px 9px #17324d33}.ao3-colour.sel{outline:4px solid #17324d}.ao3-field{width:100%;font:900 22px Nunito;padding:14px;border:4px solid #d8e2eb;border-radius:16px;background:#fff;color:#17324d}.ao3-note{font-size:14px;color:#46677c}.ao3-story{display:grid;gap:9px}.ao3-story div{padding:12px;border-radius:14px;background:#eef7ff;font-weight:800}
.ao3-egg{width:180px;height:235px;border-radius:52% 52% 48% 48%/62% 62% 38% 38%;background:var(--egg);border:10px solid #fff;box-shadow:0 0 0 18px #ffffff44,0 20px 40px #17324d44;position:relative;overflow:hidden}.ao3-egg:after{content:attr(data-mark);position:absolute;inset:0;display:grid;place-items:center;font-size:50px;filter:drop-shadow(0 3px 0 #fff8)}.ao3-egg.spots:before{content:'';position:absolute;inset:15px;background:radial-gradient(circle at 25% 25%,var(--spot) 0 12px,transparent 13px),radial-gradient(circle at 70% 55%,var(--spot) 0 19px,transparent 20px),radial-gradient(circle at 35% 80%,var(--spot) 0 10px,transparent 11px)}.ao3-egg.stars:before{content:'';position:absolute;inset:14px;background:radial-gradient(circle,var(--spot) 0 5px,transparent 6px) 0 0/45px 45px,radial-gradient(circle,var(--spot) 0 9px,transparent 10px) 20px 18px/78px 78px}.ao3-egg.waves:before{content:'';position:absolute;inset:10px;background:repeating-radial-gradient(ellipse at 50% 120%,transparent 0 19px,var(--spot) 20px 26px,transparent 27px 43px)}.ao3-egg.glow{filter:drop-shadow(0 0 24px var(--spot))}
.ao3-paint-wrap{position:relative;width:min(330px,84vw);aspect-ratio:3/4}.ao3-paint{width:100%;height:100%;touch-action:none;display:block}.ao3-tools{display:flex;flex-wrap:wrap;gap:8px;margin:10px 0}.ao3-tool{border:3px solid #fff;border-radius:13px;padding:9px 12px;background:#eef7ff;font-weight:900}.ao3-tool.sel{outline:4px solid #ffca57}.ao3-range{width:100%}
.ao3-footer{position:fixed;z-index:400010;left:0;right:0;bottom:0;padding:10px calc(14px + env(safe-area-inset-right)) calc(10px + env(safe-area-inset-bottom)) calc(14px + env(safe-area-inset-left));background:linear-gradient(transparent,#fff8df 22%);display:flex;gap:10px;justify-content:center}.ao3-footer button{min-height:56px;border:4px solid #fff;border-radius:17px;padding:12px 20px;font:900 17px Nunito}.ao3-back{background:#eef7ff;color:#17324d}.ao3-next{background:#6b4cc5;color:#fff;flex:1;max-width:520px}.ao3-error{color:#b33f5c;font-weight:900;min-height:24px}
@media(max-width:760px){.ao3-card{grid-template-columns:1fr;padding:13px;border-radius:23px}.ao3-preview{min-height:255px}.ao3-copy h1{font-size:40px}.ao3-copy h2{font-size:25px}.ao3-copy p{font-size:16px}.ao3-egg{width:130px;height:170px}.ao3-grid{grid-template-columns:1fr 1fr}.ao3-scroll{padding-bottom:125px}}
`;document.head.appendChild(css);

const root=document.createElement('section');root.id='ao3';root.innerHTML=`<div class="ao3-top"><div class="ao3-dots"></div></div><div class="ao3-scroll"><div class="ao3-card"><div class="ao3-preview"></div><div class="ao3-copy"></div></div></div><div class="ao3-footer"><button class="ao3-back">← BACK</button><button class="ao3-next">CONTINUE →</button></div>`;document.body.appendChild(root);
let step=0,painting=false,last=null;
const state={stage:'secondary',year:7,affinity:'starlight',colour:'#9b83f4',spot:'#ffe57d',pattern:'stars',glow:true,mark:'⚡',name:'Nova',brush:'#ff3b8d',size:10,tool:'brush',drawing:''};
const steps=['Story','Design','Paint','Name','World','Begin'];
const palettes=['#ff8fbd','#9b83f4','#73d8bd','#ffca57','#55c8f2','#b676d8','#ff7043','#22c55e','#111827','#ffffff','#f43f5e','#06b6d4'];
const preview=root.querySelector('.ao3-preview'),copy=root.querySelector('.ao3-copy'),next=root.querySelector('.ao3-next'),back=root.querySelector('.ao3-back');
const opt=(label,val,current,group)=>`<button class="ao3-opt ${val===current?'sel':''}" data-group="${group}" data-value="${val}">${label}</button>`;
const egg=()=>`<div class="ao3-egg ${state.pattern} ${state.glow?'glow':''}" data-mark="${state.mark}" style="--egg:${state.colour};--spot:${state.spot}"></div>`;
function dots(){root.querySelector('.ao3-dots').innerHTML=steps.map((_,i)=>`<span class="ao3-dot ${i<=step?'on':''}"></span>`).join('')}
function render(){dots();back.style.visibility=step?'visible':'hidden';next.textContent=step===steps.length-1?'BEGIN THE AWAKENING':'CONTINUE →';preview.innerHTML=egg();
if(step===0)copy.innerHTML=`<h1>ASCEND</h1><h2>Create. Explore. Grow.</h2><p>The five countries are losing their memories. Your first Ascendant is waiting inside an egg only you can create.</p><div class="ao3-story"><div>🎨 Design and paint your own egg.</div><div>🥚 Hatch one of 100 monsters—or discover a golden variant.</div><div>🧭 Explore five living countries.</div><div>⚔️ School knowledge powers battles, missions and evolution.</div></div>`;
if(step===1)copy.innerHTML=`<h2>Build your egg</h2><b>Affinity</b><div class="ao3-grid">${opt('🌿 Bloom','bloom',state.affinity,'affinity')}${opt('✦ Starlight','starlight',state.affinity,'affinity')}${opt('🌊 Tide','tide',state.affinity,'affinity')}</div><b>Shell colour</b><div class="ao3-colours">${palettes.map(c=>`<button class="ao3-colour ${c===state.colour?'sel':''}" data-shell="${c}" style="background:${c}"></button>`).join('')}</div><b>Second colour</b><div class="ao3-colours">${palettes.map(c=>`<button class="ao3-colour ${c===state.spot?'sel':''}" data-spot="${c}" style="background:${c}"></button>`).join('')}</div><b>Pattern</b><div class="ao3-grid">${opt('Spots','spots',state.pattern,'pattern')}${opt('Stars','stars',state.pattern,'pattern')}${opt('Waves','waves',state.pattern,'pattern')}${opt('Plain','plain',state.pattern,'pattern')}</div><b>Symbol</b><div class="ao3-grid">${['⚡','✦','❖','☾','♥','★','🌈','🔥'].map(m=>opt(m,m,state.mark,'mark')).join('')}</div><label><input class="ao3-glow" type="checkbox" ${state.glow?'checked':''}> Magical glow</label>`;
if(step===2){preview.innerHTML=`<div class="ao3-paint-wrap"><canvas class="ao3-paint" width="360" height="480"></canvas></div>`;copy.innerHTML=`<h2>Paint it yourself</h2><p>Draw anything you like with as many colours as you want. Your artwork is saved on the egg.</p><b>Paint colours</b><div class="ao3-colours">${palettes.map(c=>`<button class="ao3-colour ${c===state.brush?'sel':''}" data-brush="${c}" style="background:${c}"></button>`).join('')}</div><div class="ao3-tools"><button class="ao3-tool ${state.tool==='brush'?'sel':''}" data-tool="brush">🖌️ Brush</button><button class="ao3-tool ${state.tool==='eraser'?'sel':''}" data-tool="eraser">🧽 Eraser</button><button class="ao3-tool" data-clear>Clear art</button></div><label>Brush size <input class="ao3-range" type="range" min="3" max="30" value="${state.size}"></label><p class="ao3-note">Paint is clipped to the egg shape, so children can freely draw without colouring outside it.</p>`;setupCanvas()}
if(step===3)copy.innerHTML=`<h2>The egg hears you</h2><p>A heartbeat answers from inside. What will your first companion be called?</p><input class="ao3-field ao3-name" maxlength="18" value="${state.name}" autocomplete="off" inputmode="text"><div class="ao3-error"></div><p class="ao3-note">The species remains a surprise until hatching. Press Continue or the keyboard Return key.</p>`;
if(step===4){preview.innerHTML=`<div style="font-size:110px">🗺️</div>`;copy.innerHTML=`<h2>Five countries are waiting</h2><div class="ao3-story"><div>🌿 Verdara — ecosystems, stories and community</div><div>☀️ Solara — trade, geometry and architecture</div><div>🌊 Mizuno — seasons, engineering and poetry</div><div>⛰️ Amaru — patterns, farming and astronomy</div><div>❄️ Aurora Reach — weather, navigation and safety</div></div><p>Meet NPCs, accept missions, battle subject trainers, challenge gyms and find monsters in their habitats.</p>`}
if(step===5){const years=state.stage==='primary'?[1,2,3,4,5,6]:[7,8,9,10,11,12];copy.innerHTML=`<h2>Choose where to begin</h2><p>School year sets the first doorway only. ASCEND quietly diagnoses every skill and moves each one up or down independently.</p><div class="ao3-grid">${opt('PRIMARY · Years 1–6','primary',state.stage,'stage')}${opt('SECONDARY · Years 7–12','secondary',state.stage,'stage')}</div><div class="ao3-grid">${years.map(y=>opt(`Year ${y}`,String(y),String(state.year),'year')).join('')}</div><p class="ao3-note">The Awakening feels like story encounters, not a school test.</p>`}
bind();requestAnimationFrame(()=>root.querySelector('.ao3-scroll').scrollTo({top:0,behavior:'instant'}));}
function bind(){root.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{const g=b.dataset.group,v=b.dataset.value;if(g==='year')state.year=+v;else state[g]=v;if(g==='stage')state.year=v==='primary'?1:7;render()});root.querySelectorAll('[data-shell]').forEach(b=>b.onclick=()=>{state.colour=b.dataset.shell;render()});root.querySelectorAll('[data-spot]').forEach(b=>b.onclick=()=>{state.spot=b.dataset.spot;render()});root.querySelector('.ao3-glow')?.addEventListener('change',e=>{state.glow=e.target.checked;render()});const name=root.querySelector('.ao3-name');if(name){name.addEventListener('input',e=>state.name=e.target.value.replace(/[^a-zA-Z0-9 '\-]/g,'').slice(0,18));name.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();goNext()}})}root.querySelectorAll('[data-brush]').forEach(b=>b.onclick=()=>{state.brush=b.dataset.brush;state.tool='brush';render()});root.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{state.tool=b.dataset.tool;render()});root.querySelector('[data-clear]')?.addEventListener('click',()=>{state.drawing='';render()});root.querySelector('.ao3-range')?.addEventListener('input',e=>state.size=+e.target.value)}
function setupCanvas(){const c=root.querySelector('.ao3-paint');if(!c)return;const x=c.getContext('2d');function base(){x.clearRect(0,0,c.width,c.height);x.save();x.beginPath();x.ellipse(180,235,135,195,0,0,Math.PI*2);x.clip();x.fillStyle=state.colour;x.fillRect(0,0,c.width,c.height);if(state.drawing){const im=new Image();im.onload=()=>x.drawImage(im,0,0,c.width,c.height);im.src=state.drawing}x.restore();x.lineWidth=9;x.strokeStyle='#fff';x.beginPath();x.ellipse(180,235,135,195,0,0,Math.PI*2);x.stroke()}base();const pos=e=>{const r=c.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:(p.clientX-r.left)*c.width/r.width,y:(p.clientY-r.top)*c.height/r.height}};const start=e=>{e.preventDefault();painting=true;last=pos(e)};const move=e=>{if(!painting)return;e.preventDefault();const p=pos(e);x.save();x.beginPath();x.ellipse(180,235,135,195,0,0,Math.PI*2);x.clip();x.globalCompositeOperation=state.tool==='eraser'?'destination-out':'source-over';x.strokeStyle=state.brush;x.lineWidth=state.size;x.lineCap='round';x.lineJoin='round';x.beginPath();x.moveTo(last.x,last.y);x.lineTo(p.x,p.y);x.stroke();x.restore();last=p};const end=()=>{if(!painting)return;painting=false;state.drawing=c.toDataURL('image/png')};c.addEventListener('pointerdown',start);c.addEventListener('pointermove',move);window.addEventListener('pointerup',end)}
function goNext(){if(step===3&&!state.name.trim()){root.querySelector('.ao3-error').textContent='Give your companion a name first.';root.querySelector('.ao3-name').focus();return}if(step<steps.length-1){step++;render();return}const p=load();p.stage=state.stage;p.schoolYear=state.year;p.egg=`${state.affinity[0].toUpperCase()+state.affinity.slice(1)} Custom Egg`;p.companion=state.name.trim()||'Nova';p.diagnosticComplete=false;p.diagnosticIndex=0;p.onboardingComplete=true;p.eggDesign={affinity:state.affinity,colour:state.colour,spot:state.spot,pattern:state.pattern,glow:state.glow,mark:state.mark,drawing:state.drawing,version:3};save(p);location.reload()}
next.onclick=goNext;back.onclick=()=>{if(step){step--;render()}};
const profile=load();if(!profile.onboardingComplete&&!profile.diagnosticComplete){document.body.classList.add('ao3-open');root.classList.add('open');render()}
