import { hatchCreature, getSpecies } from './creature-system.js';

const ROOT = document.getElementById('teacher-demo');
const KEY = 'ascend_teacher_demo_v2';
const load = () => { try { return JSON.parse(localStorage.getItem(KEY) || '{}'); } catch { return {}; } };
const save = (s) => localStorage.setItem(KEY, JSON.stringify(s));
const fresh = () => ({
  stage:'arrival', level:1, xp:0, coins:0,
  egg:{familyId:'bloom',shell:'#9b6de3',accent:'#ffd65a',pattern:'spots',nickname:'Nova'},
  creature:null, eggs:[], evidence:[], subjectMastery:{mathematics:.2,english:.2,science:.2}, assignment:null
});
let state = {...fresh(), ...load()};
let player = {x:44,y:62};
let hatchEnergy = 0, qIndex = 0, battleHp = 100;
const palette=['#9b6de3','#73d8bd','#ffca57','#ff8fb3','#5bb8ff','#84d96b','#ff845b','#f7f4e8','#36516c','#ce60f2','#ff477e','#2ecbb9'];
const hatchQs=[
 {subject:'mathematics',q:'Mira has 6 maps and finds 3 more. How many maps now?',a:'9',opts:['8','9','10','12'],hint:'Count forward three from six.',explain:'6 + 3 = 9.'},
 {subject:'english',q:'Which word means a machine that safely warms an egg?',a:'incubator',opts:['library','incubator','bridge','market'],hint:'It is the machine beside you.',explain:'An incubator safely warms an egg while it develops.'},
 {subject:'mathematics',q:'Half of 12 hatch crystals is…',a:'6',opts:['4','5','6','12'],hint:'Split 12 into two equal groups.',explain:'12 divided by 2 equals 6.'},
 {subject:'science',q:'Plants use sunlight, water and which gas to make food?',a:'carbon dioxide',opts:['helium','carbon dioxide','steam','nitrogen only'],hint:'People breathe this gas out.',explain:'Plants use carbon dioxide during photosynthesis.'}
];
const battleQs=[
 {subject:'mathematics',q:'A trainer has 4 groups of 6 crystals. How many crystals?',a:'24',opts:['10','20','24','28'],hint:'Multiply 4 by 6.',explain:'4 groups of 6 equals 24.'},
 {subject:'english',q:'Choose the sentence with correct punctuation.',a:'Mira said, “Follow the path.”',opts:['Mira said follow the path','Mira said, “Follow the path.”','mira said Follow the path','Mira said follow, the path.'],hint:'Look for a capital letter, comma and full stop.',explain:'Direct speech needs punctuation and quotation marks.'},
 {subject:'science',q:'Which is a living part of a forest ecosystem?',a:'tree',opts:['sunlight','water','tree','rock'],hint:'Living things grow and reproduce.',explain:'A tree is living; sunlight, water and rocks are non-living factors.'}
];

const css=document.createElement('style');css.textContent=`
*{box-sizing:border-box}body{margin:0;font-family:Nunito,system-ui,sans-serif;color:#17324d;overflow:hidden;touch-action:manipulation;background:#7fd477}
#td2{position:fixed;inset:0;overflow:hidden;background:#7fd477}.world{position:absolute;inset:0;background:linear-gradient(#7fd477 0 36%,#ecd48f 36% 62%,#7fd477 62%)}
.tree{position:absolute;width:44px;height:82px}.tree:before{content:'';position:absolute;left:13px;bottom:0;width:18px;height:38px;background:#795538}.tree:after{content:'';position:absolute;left:0;top:0;width:44px;height:48px;border-radius:50%;background:#3f9752}
.house{position:absolute;left:12%;top:66%;width:48%;height:26%;background:#fff8df;border:8px solid #fff;border-radius:18px}.house:before{content:'';position:absolute;left:-8%;top:-34%;width:116%;height:42%;background:#d96f83;clip-path:polygon(50% 0,100% 100%,0 100%)}.house:after{content:'';position:absolute;left:42%;bottom:0;width:18%;height:35%;background:#39734a;border:6px solid #fff}
.incubator{position:absolute;left:69%;top:18%;width:24%;height:18%;border-radius:20px;background:#e9e2ff;border:7px solid #fff;display:grid;place-items:center;font-weight:900}.incubator:before{content:'🥚';font-size:54px}.trainer{position:absolute;left:82%;top:49%;font-weight:900;text-align:center}.mira{position:absolute;left:67%;top:35%;font-weight:900;text-align:center}.npcbody{width:58px;height:80px;margin:auto;border-radius:50% 50% 40% 40%;background:#73d8bd;border:5px solid #fff}.trainer .npcbody{background:#ffca57}
.player{position:absolute;width:58px;height:78px;transform:translate(-50%,-50%);transition:left .08s linear,top .08s linear;z-index:3}.player:before{content:'';position:absolute;left:5px;top:24px;width:48px;height:52px;border-radius:48% 48% 38% 38%;background:#59a9e8;border:4px solid #fff}.player:after{content:'';position:absolute;left:12px;top:0;width:34px;height:34px;border-radius:50%;background:#f5c69d;border:4px solid #fff}.carried{position:absolute;right:-11px;top:36px;width:25px;height:33px;border-radius:50%;background:var(--shell);border:4px solid #fff}.companion{position:absolute;left:-30px;top:48px;width:30px;height:30px;border-radius:50%;background:#8d72e8;border:4px solid #fff}
.hud{position:absolute;left:10px;right:10px;top:max(10px,env(safe-area-inset-top));z-index:10;display:flex;gap:8px;justify-content:space-between}.card{background:#fff8dff2;border:5px solid #fff;border-radius:17px;padding:9px 12px;font-weight:900}.adult,.reset{border:0;border-radius:11px;background:#17324d;color:#fff;font-weight:900;padding:10px}.objective{position:absolute;z-index:9;top:88px;left:50%;transform:translateX(-50%);width:90%;background:#fff8dff2;border:5px solid #fff;border-radius:16px;padding:10px;text-align:center;font-weight:900}
.controls{position:absolute;z-index:20;left:14px;right:14px;bottom:max(14px,env(safe-area-inset-bottom));display:flex;justify-content:space-between;align-items:end}.dpad{width:150px;height:150px;display:grid;grid-template:repeat(3,1fr)/repeat(3,1fr);gap:4px}.move{border:5px solid #fff;border-radius:16px;background:#ffffffdc;font:900 24px system-ui;touch-action:none}.up{grid-column:2}.left{grid-row:2;grid-column:1}.right{grid-row:2;grid-column:3}.down{grid-row:3;grid-column:2}.act{width:92px;height:92px;border-radius:50%;border:7px solid #fff;background:#ffca57;font:900 20px system-ui}.act.ready{background:#73d8bd;animation:pulse .7s infinite alternate}@keyframes pulse{to{transform:scale(1.08)}}
.prompt{position:absolute;z-index:12;bottom:175px;left:50%;transform:translateX(-50%);background:#17324de8;color:#fff;border:4px solid #fff;border-radius:14px;padding:9px 12px;font-weight:900;display:none}.prompt.show{display:block}
.modal{position:absolute;inset:0;z-index:50;background:#17324ddd;display:none;place-items:center;padding:12px;overflow:auto}.modal.open{display:grid}.panel{width:min(720px,95vw);max-height:90dvh;overflow:auto;background:#fff8df;border:7px solid #fff;border-radius:25px;padding:16px;text-align:center}.panel h1,.panel h2{color:#6b4cc5}.actions{display:grid;gap:9px}.btn{min-height:52px;border:4px solid #fff;border-radius:14px;padding:11px;background:#73d8bd;font-weight:900}.primary{background:#8d72e8;color:#fff}.gold{background:#ffca57}.alt{background:#eef7ff}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.option{min-height:46px;border:4px solid #fff;border-radius:12px;background:#eef7ff;font-weight:900}.option.sel{background:#ffca57}.colours{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin:8px 0}.colour{aspect-ratio:1;border-radius:50%;border:4px solid #fff}.colour.sel{outline:4px solid #6b4cc5}.input{width:100%;padding:12px;border:4px solid #d7e2e9;border-radius:13px;font:800 17px system-ui}.egg{width:145px;height:185px;margin:10px auto;border-radius:50% 50% 46% 46%/58% 58% 42% 42%;border:8px solid #fff;position:relative;overflow:hidden;background:var(--shell)}.pattern{position:absolute;inset:0;display:grid;place-items:center;color:var(--accent);font-size:34px;white-space:pre;line-height:1.2}.answers{display:grid;grid-template-columns:1fr 1fr;gap:9px}.meter{height:22px;background:#dfe7ed;border-radius:999px;overflow:hidden}.meter span{display:block;height:100%;background:linear-gradient(90deg,#73d8bd,#ffca57,#8d72e8)}.feedback{min-height:25px;font-weight:900}.support{display:flex;gap:8px;justify-content:center;flex-wrap:wrap}.support button{padding:9px;border:3px solid #fff;border-radius:10px;font-weight:900}.table{width:100%;border-collapse:collapse}.table td,.table th{padding:8px;border-bottom:1px solid #ccd8df;text-align:left}
@media(max-width:600px){.hud{font-size:13px}.card{padding:7px}.objective{top:82px;font-size:13px}.dpad{width:132px;height:132px}.act{width:86px;height:86px}.grid{grid-template-columns:1fr}.answers{grid-template-columns:1fr}.panel{padding:12px}.colours{grid-template-columns:repeat(6,1fr)}}`;
document.head.appendChild(css);

ROOT.innerHTML=`<section id="td2"><div class="world"><div class="tree" style="left:6%;top:20%"></div><div class="tree" style="left:73%;top:7%"></div><div class="tree" style="left:58%;top:66%"></div><div class="tree" style="left:90%;top:72%"></div><div class="house"></div><div class="incubator">INCUBATOR</div><div class="mira"><div>Mira</div><div class="npcbody"></div></div><div class="trainer"><div>Trainer Sol</div><div class="npcbody"></div></div><div class="player"></div></div><div class="hud"><div class="card stats"></div><div class="card"><button class="adult">ADULT HUB</button> <button class="reset">RESET</button></div></div><div class="objective"></div><div class="prompt"></div><div class="controls"><div class="dpad"><button class="move up" data-dx="0" data-dy="-1">▲</button><button class="move left" data-dx="-1" data-dy="0">◀</button><button class="move right" data-dx="1" data-dy="0">▶</button><button class="move down" data-dx="0" data-dy="1">▼</button></div><button class="act">ACT</button></div><div class="modal"><div class="panel"></div></div></section>`;

const $=s=>ROOT.querySelector(s), playerEl=$('.player'), stats=$('.stats'), objective=$('.objective'), prompt=$('.prompt'), modal=$('.modal'), panel=$('.panel'), act=$('.act');
const persist=()=>save(state); const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)); const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const positions={mira:{x:70,y:42},incubator:{x:80,y:25},trainer:{x:85,y:54}};
let held={x:0,y:0}, timer=null, near=null;
function renderPlayer(){playerEl.style.left=player.x+'%';playerEl.style.top=player.y+'%';playerEl.innerHTML=(state.stage==='carryEgg'?`<span class="carried" style="--shell:${state.egg.shell}"></span>`:'')+(state.creature?'<span class="companion"></span>':'')}
function hud(){stats.textContent=`Level ${state.level} · XP ${state.xp} · Coins ${state.coins} · ${state.creature?state.creature.nickname:'No companion yet'}`;objective.textContent=state.stage==='arrival'?'Mira is walking over to meet you…':state.stage==='meetMira'?'Talk with Mira.':state.stage==='carryEgg'?'Carry the egg to the nearby incubator.':state.stage==='hatching'?'Power the incubator with learning.':state.stage==='mission'?'Walk to Trainer Sol for your first mission battle.':'Demo complete — open the Adult Hub.'}
function proximity(){near=null;if(state.stage==='meetMira'&&dist(player,positions.mira)<12)near='mira';if(state.stage==='carryEgg'&&dist(player,positions.incubator)<13)near='incubator';if(state.stage==='mission'&&dist(player,positions.trainer)<13)near='trainer';act.classList.toggle('ready',!!near);prompt.classList.toggle('show',!!near);prompt.textContent=near==='mira'?'ACT: Talk to Mira':near==='incubator'?'ACT: Use incubator':near==='trainer'?'ACT: Challenge Trainer Sol':''}
function step(dx,dy){if(modal.classList.contains('open')||state.stage==='arrival')return;player.x=clamp(player.x+dx*1.3,4,96);player.y=clamp(player.y+dy*1.3,16,88);renderPlayer();proximity()}
function startMove(dx,dy){stopMove();held={x:dx,y:dy};step(dx,dy);timer=setInterval(()=>step(dx,dy),65)}function stopMove(){if(timer)clearInterval(timer);timer=null;held={x:0,y:0}}
ROOT.querySelectorAll('.move').forEach(b=>{const dx=+b.dataset.dx,dy=+b.dataset.dy;['touchstart','mousedown','pointerdown'].forEach(ev=>b.addEventListener(ev,e=>{e.preventDefault();startMove(dx,dy)},{passive:false}));['touchend','touchcancel','mouseup','mouseleave','pointerup','pointercancel'].forEach(ev=>b.addEventListener(ev,e=>{e.preventDefault();stopMove()},{passive:false}))});
function open(html){panel.innerHTML=html;modal.classList.add('open')}function close(){modal.classList.remove('open')}
function patternText(){return state.egg.pattern==='spots'?'●  ●\n  ●':state.egg.pattern==='stars'?'★  ✦\n✦  ★':'≈≈≈\n≈≈≈\n≈≈≈'}
function eggHtml(){return `<div class="egg" style="--shell:${state.egg.shell};--accent:${state.egg.accent}"><div class="pattern">${patternText()}</div></div>`}
function record(q,correct){state.evidence.push({at:new Date().toISOString(),subject:q.subject,correct});state.subjectMastery[q.subject]=clamp((state.subjectMastery[q.subject]||.2)+(correct?.04:-.015),0,1);persist()}
function intro(){open(`<h1>Mira</h1><p>Welcome to Verdara. ASCEND is a creature-collecting school adventure across five countries. Learning powers hatching, missions and battles.</p><p>I have your first egg. Carry it to the nearby incubator.</p><div class="actions"><button class="btn primary" data-ok>ACCEPT THE EGG</button></div>`);panel.querySelector('[data-ok]').onclick=()=>{state.stage='carryEgg';persist();close();hud();renderPlayer()}}
function customiser(){open(`<h2>Incubator Shell Studio</h2><p>Customise the shell. The monster remains random.</p>${eggHtml()}<b>Affinity</b><div class="grid">${[['bloom','🌿 Bloom'],['starlight','✦ Starlight'],['tide','🌊 Tide']].map(([v,l])=>`<button class="option ${state.egg.familyId===v?'sel':''}" data-family="${v}">${l}</button>`).join('')}</div><b>Shell colour</b><div class="colours">${palette.map(c=>`<button class="colour ${state.egg.shell===c?'sel':''}" data-shell="${c}" style="background:${c}"></button>`).join('')}</div><b>Pattern colour</b><div class="colours">${palette.map(c=>`<button class="colour ${state.egg.accent===c?'sel':''}" data-accent="${c}" style="background:${c}"></button>`).join('')}</div><b>Pattern</b><div class="grid">${['spots','stars','waves'].map(v=>`<button class="option ${state.egg.pattern===v?'sel':''}" data-pattern="${v}">${v}</button>`).join('')}</div><label><b>Nickname</b><input class="input" maxlength="18" value="${state.egg.nickname}"></label><div class="actions"><button class="btn primary" data-start>START HATCHING</button></div>`);panel.querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>{state.egg.familyId=b.dataset.family;persist();customiser()});panel.querySelectorAll('[data-shell]').forEach(b=>b.onclick=()=>{state.egg.shell=b.dataset.shell;persist();customiser()});panel.querySelectorAll('[data-accent]').forEach(b=>b.onclick=()=>{state.egg.accent=b.dataset.accent;persist();customiser()});panel.querySelectorAll('[data-pattern]').forEach(b=>b.onclick=()=>{state.egg.pattern=b.dataset.pattern;persist();customiser()});panel.querySelector('.input').oninput=e=>{state.egg.nickname=e.target.value.slice(0,18);persist()};panel.querySelector('[data-start]').onclick=()=>{state.stage='hatching';hatchEnergy=0;qIndex=0;persist();hatchQ()}}
function hatchQ(){const q=hatchQs[qIndex%hatchQs.length],power=20+state.level*5;open(`<h2>Incubator Power</h2>${eggHtml()}<div class="meter"><span style="width:${hatchEnergy}%"></span></div><p>Each correct answer creates <b>${power}</b> energy.</p><h3>${q.q}</h3><div class="answers">${q.opts.map(o=>`<button class="btn" data-a="${o}">${o}</button>`).join('')}</div><div class="support"><button data-h>💡 Hint</button><button data-e>📖 Explain</button></div><div class="feedback"></div>`);panel.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{const f=panel.querySelector('.feedback');if(b.dataset.a!==q.a){record(q,false);f.textContent='Not yet. Use Hint or Explain.';return}record(q,true);hatchEnergy=Math.min(100,hatchEnergy+power);f.textContent=`Correct! +${power} energy.`;setTimeout(()=>hatchEnergy>=100?finishHatch():(qIndex++,hatchQ()),400)});panel.querySelector('[data-h]').onclick=()=>panel.querySelector('.feedback').textContent=q.hint;panel.querySelector('[data-e]').onclick=()=>panel.querySelector('.feedback').textContent=q.explain}
function finishHatch(){const c=hatchCreature(state.egg.familyId),s=getSpecies(c.speciesId);c.nickname=state.egg.nickname||s?.name||'Nova';state.creature=c;state.stage='mission';state.xp+=20;persist();open(`<h1>${c.nickname} hatched!</h1><p><b>${s?.name||'Ascendant'}</b> · ${c.rarity.toUpperCase()}</p><p>Meet Trainer Sol for your first subject battle.</p><div class="actions"><button class="btn primary" data-go>LEAVE INCUBATOR</button></div>`);panel.querySelector('[data-go]').onclick=()=>{close();hud();renderPlayer()}}
function battle(){battleHp=100;qIndex=0;battleQ()}
function battleQ(){const q=battleQs[qIndex%battleQs.length],damage=20+state.level*8;open(`<h2>Trainer Battle</h2><p>${state.creature?.nickname||'Companion'} vs Spriglet</p><div class="meter"><span style="width:${battleHp}%"></span></div><p>Correct answers deal <b>${damage}</b> damage.</p><h3>${q.q}</h3><div class="answers">${q.opts.map(o=>`<button class="btn" data-a="${o}">${o}</button>`).join('')}</div><div class="support"><button data-h>💡 Hint</button><button data-e>📖 Explain</button></div><div class="feedback"></div>`);panel.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{const f=panel.querySelector('.feedback');if(b.dataset.a!==q.a){record(q,false);f.textContent='Blocked. Read the explanation and try again.';return}record(q,true);battleHp=Math.max(0,battleHp-damage);f.textContent=`Correct! ${damage} damage.`;setTimeout(()=>battleHp<=0?win():(qIndex++,battleQ()),400)});panel.querySelector('[data-h]').onclick=()=>panel.querySelector('.feedback').textContent=q.hint;panel.querySelector('[data-e]').onclick=()=>panel.querySelector('.feedback').textContent=q.explain}
function win(){state.stage='complete';state.level=2;state.xp+=80;state.coins+=50;state.eggs.push({id:Date.now(),familyId:'bloom'});persist();open(`<h1>Mission complete!</h1><p>You earned a Verdara egg.</p><div class="actions"><button class="btn gold" data-report>OPEN PARENT REPORT</button><button class="btn primary" data-close>RETURN TO TOWN</button></div>`);panel.querySelector('[data-report]').onclick=parentReport;panel.querySelector('[data-close]').onclick=()=>{close();hud()}}
function interact(){if(near==='mira')intro();else if(near==='incubator')customiser();else if(near==='trainer')battle();else{prompt.textContent='Move closer to Mira, the incubator or Trainer Sol.';prompt.classList.add('show');setTimeout(()=>{if(!near)prompt.classList.remove('show')},900)}}
act.addEventListener('touchstart',e=>{e.preventDefault();interact()},{passive:false});act.addEventListener('click',interact);
function grade(v){return v>=.85?'A':v>=.7?'B':v>=.55?'C':v>=.4?'D':'E'}
function parentReport(){const attempts=state.evidence.length,correct=state.evidence.filter(e=>e.correct).length,accuracy=attempts?Math.round(correct/attempts*100):0;open(`<h1>Live Parent Report</h1><table class="table"><tr><th>Measure</th><th>Current evidence</th></tr><tr><td>Level</td><td>${state.level}</td></tr><tr><td>Attempts</td><td>${attempts}</td></tr><tr><td>Accuracy</td><td>${accuracy}%</td></tr>${Object.entries(state.subjectMastery).map(([s,v])=>`<tr><td>${s}</td><td>${Math.round(v*100)}% · Band ${grade(v)}</td></tr>`).join('')}<tr><td>Teacher target</td><td>${state.assignment?`${state.assignment.subject}: ${state.assignment.skill}`:'None set'}</td></tr></table><div class="actions"><button class="btn alt" data-x>CLOSE</button></div>`);panel.querySelector('[data-x]').onclick=close}
function teacher(){open(`<h1>Teacher Workspace</h1><select class="input subject"><option>mathematics</option><option>english</option><option>science</option></select><input class="input skill" placeholder="Skill or topic"><textarea class="input notes" rows="4" placeholder="Instructions or homework"></textarea><div class="actions"><button class="btn primary" data-save>SAVE TARGET</button><button class="btn alt" data-x>CLOSE</button></div>`);panel.querySelector('[data-save]').onclick=()=>{const skill=panel.querySelector('.skill').value.trim();if(!skill)return;state.assignment={subject:panel.querySelector('.subject').value,skill,notes:panel.querySelector('.notes').value.trim()};persist();parentReport()};panel.querySelector('[data-x]').onclick=close}
function adultHub(){open(`<h1>Adult Hub</h1><div class="actions"><button class="btn gold" data-p>PARENT REPORT</button><button class="btn primary" data-t>TEACHER WORKSPACE</button><button class="btn alt" data-x>CLOSE</button></div>`);panel.querySelector('[data-p]').onclick=parentReport;panel.querySelector('[data-t]').onclick=teacher;panel.querySelector('[data-x]').onclick=close}
$('.adult').onclick=adultHub;$('.reset').onclick=()=>{localStorage.removeItem(KEY);location.reload()};
window.addEventListener('mouseup',stopMove);window.addEventListener('touchend',stopMove,{passive:true});
renderPlayer();hud();proximity();
if(state.stage==='arrival'){setTimeout(()=>{state.stage='meetMira';player={x:58,y:55};persist();renderPlayer();hud();proximity();intro()},700)}
