import { hatchCreature, getSpecies } from './creature-system.js';

const ROOT = document.getElementById('teacher-demo');
const KEY = 'ascend_teacher_demo_v1';
const load = () => { try { return JSON.parse(localStorage.getItem(KEY) || '{}'); } catch { return {}; } };
const save = (state) => localStorage.setItem(KEY, JSON.stringify(state));

const initialState = () => ({
  version: 1,
  stage: 'arrival',
  level: 1,
  xp: 0,
  coins: 0,
  egg: { familyId: 'bloom', shell: '#9b6de3', accent: '#ffd65a', pattern: 'spots', nickname: 'Nova' },
  creature: null,
  eggs: [],
  activeCreatureUid: '',
  evidence: [],
  subjectMastery: { mathematics: 0.2, english: 0.2, science: 0.2 },
  assignment: null,
  missionComplete: false,
});

let state = { ...initialState(), ...load() };
const persist = () => save(state);

const css = document.createElement('style');
css.textContent = `
*{box-sizing:border-box}body{font-family:Nunito,system-ui,sans-serif;color:#17324d;touch-action:none;overscroll-behavior:none;-webkit-tap-highlight-color:transparent}
#td-game{position:fixed;inset:0;overflow:hidden;background:#72ca72}#td-game canvas{position:absolute;inset:0;width:100%;height:100%;display:block}
.td-top{position:absolute;z-index:5;left:10px;right:10px;top:max(10px,env(safe-area-inset-top));display:flex;justify-content:space-between;gap:8px;pointer-events:none}.td-card{pointer-events:auto;background:#fff8dff3;border:4px solid #fff;border-radius:16px;padding:9px 12px;font-weight:900;box-shadow:0 6px 18px #17324d33}.td-top button{border:0;border-radius:11px;padding:10px 12px;font-weight:900;background:#17324d;color:#fff;touch-action:manipulation}
.td-objective{position:absolute;z-index:5;top:82px;left:50%;transform:translateX(-50%);width:min(600px,90vw);background:#fff8dff3;border:4px solid #fff;border-radius:15px;padding:10px 13px;text-align:center;font-weight:900;pointer-events:none}
.td-prompt{position:absolute;z-index:7;left:50%;bottom:118px;transform:translateX(-50%);width:min(560px,82vw);background:#17324de8;color:#fff;border:4px solid #fff;border-radius:15px;padding:10px;text-align:center;font-weight:900;display:none}.td-prompt.show{display:block}
.td-controls{position:absolute;z-index:8;left:0;right:0;bottom:max(14px,env(safe-area-inset-bottom));padding:0 18px;display:flex;justify-content:space-between;align-items:end;pointer-events:none}.td-stick{width:124px;height:124px;border:5px solid #ffffffdd;border-radius:50%;background:#17324d38;position:relative;pointer-events:auto;touch-action:none}.td-knob{position:absolute;left:50%;top:50%;width:58px;height:58px;margin:-29px;border-radius:50%;border:5px solid #fff;background:#ffffffec;box-shadow:0 5px 14px #17324d44}.td-act{pointer-events:auto;width:88px;height:88px;border:6px solid #fff;border-radius:50%;background:#ffca57;color:#553a05;font:900 18px Nunito;touch-action:manipulation;box-shadow:0 10px 28px #17324d44}.td-act.ready{background:#73d8bd;animation:pulse .7s ease-in-out infinite alternate}@keyframes pulse{to{transform:scale(1.08)}}
.td-modal{position:absolute;z-index:30;inset:0;display:none;place-items:center;padding:12px;background:#17324ddd;overflow:auto}.td-modal.open{display:grid}.td-panel{width:min(720px,95vw);max-height:90dvh;overflow:auto;background:#fff8df;border:7px solid #fff;border-radius:25px;padding:18px;text-align:center;box-shadow:0 20px 60px #0005}.td-panel h1,.td-panel h2{color:#6b4cc5;margin:5px 0}.td-panel p{font-size:16px;line-height:1.45}.td-actions{display:grid;gap:9px;margin-top:14px}.td-btn{min-height:52px;border:4px solid #fff;border-radius:14px;padding:11px 14px;background:#73d8bd;color:#17324d;font:900 16px Nunito;touch-action:manipulation}.td-btn.primary{background:#8d72e8;color:#fff}.td-btn.gold{background:#ffca57}.td-btn.alt{background:#eef7ff}.td-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.td-option{min-height:46px;border:4px solid #fff;border-radius:12px;background:#eef7ff;font-weight:900}.td-option.sel{background:#ffca57}.td-colours{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin:8px 0}.td-colour{aspect-ratio:1;border-radius:50%;border:4px solid #fff}.td-colour.sel{outline:4px solid #6b4cc5}.td-input{width:100%;padding:12px;border:4px solid #d7e2e9;border-radius:13px;font:800 17px Nunito}.td-egg{width:145px;height:185px;margin:10px auto;border-radius:50% 50% 46% 46%/58% 58% 42% 42%;border:8px solid #fff;position:relative;overflow:hidden;background:var(--shell);box-shadow:0 13px 28px #17324d33}.td-egg:after{position:absolute;inset:0;display:grid;place-items:center;color:var(--accent);font-size:34px;line-height:1.2;white-space:pre;text-align:center}.td-egg.spots:after{content:'●  ●\A   ●'}.td-egg.stars:after{content:'★  ✦\A ✦  ★'}.td-egg.waves:after{content:'≈≈≈\A≈≈≈\A≈≈≈'}
.td-meter{height:22px;background:#dfe7ed;border-radius:999px;overflow:hidden;margin:12px 0}.td-meter span{display:block;height:100%;background:linear-gradient(90deg,#73d8bd,#ffca57,#8d72e8);transition:width .35s}.td-q{font-size:22px;font-weight:900;margin:12px 0}.td-answers{display:grid;grid-template-columns:1fr 1fr;gap:9px}.td-support{display:flex;gap:8px;justify-content:center;flex-wrap:wrap;margin-top:9px}.td-support button{border:3px solid #fff;border-radius:11px;padding:9px 11px;font-weight:900;background:#eef7ff}.td-feedback{min-height:24px;font-weight:900;margin-top:9px}.td-table{width:100%;border-collapse:collapse}.td-table td,.td-table th{padding:9px;border-bottom:1px solid #d7e2e9;text-align:left}.td-tabs{display:flex;gap:8px;flex-wrap:wrap;justify-content:center;margin-bottom:10px}
@media(max-width:600px){.td-panel{padding:13px}.td-grid{grid-template-columns:1fr}.td-answers{grid-template-columns:1fr}.td-stick{width:112px;height:112px}.td-act{width:82px;height:82px}.td-objective{font-size:13px;top:74px}.td-colours{grid-template-columns:repeat(6,1fr)}}
`;
document.head.appendChild(css);

ROOT.innerHTML = `<section id="td-game"><canvas></canvas><div class="td-top"><div class="td-card td-stats"></div><div class="td-card"><button class="td-adult">ADULT HUB</button> <button class="td-reset">RESET DEMO</button></div></div><div class="td-objective"></div><div class="td-prompt"></div><div class="td-controls"><div class="td-stick"><div class="td-knob"></div></div><button class="td-act">ACT</button></div><div class="td-modal"><div class="td-panel"></div></div></section>`;

const game = document.getElementById('td-game');
const canvas = game.querySelector('canvas');
const ctx = canvas.getContext('2d');
const stats = game.querySelector('.td-stats');
const objective = game.querySelector('.td-objective');
const prompt = game.querySelector('.td-prompt');
const modal = game.querySelector('.td-modal');
const panel = game.querySelector('.td-panel');
const stick = game.querySelector('.td-stick');
const knob = game.querySelector('.td-knob');
const act = game.querySelector('.td-act');
let dpr = 1, last = performance.now(), move = {x:0,y:0}, near = null;
let player = {x:360,y:880,speed:250};
let mira = {x:880,y:760,targetX:470,targetY:820,walking:state.stage==='arrival'};
const incubator = {x:750,y:430};
const trainer = {x:970,y:900};
let hatchEnergy = 0, questionIndex = 0, battleHp = 100;

const palette = ['#9b6de3','#73d8bd','#ffca57','#ff8fb3','#5bb8ff','#84d96b','#ff845b','#f7f4e8','#36516c','#ce60f2','#ff477e','#2ecbb9'];
const hatchQuestions = [
  {subject:'mathematics',q:'Mira has 6 maps and finds 3 more. How many maps now?',a:'9',opts:['8','9','10','12'],hint:'Count forward three from six.',explain:'6 + 3 = 9.'},
  {subject:'english',q:'Which word means a machine that safely warms an egg?',a:'incubator',opts:['library','incubator','bridge','market'],hint:'It is the machine beside you.',explain:'An incubator keeps an egg safe and warm while it develops.'},
  {subject:'mathematics',q:'Half of 12 hatch crystals is…',a:'6',opts:['4','5','6','12'],hint:'Split 12 into two equal groups.',explain:'12 divided by 2 equals 6.'},
  {subject:'science',q:'Plants use sunlight, water and which gas to make food?',a:'carbon dioxide',opts:['helium','carbon dioxide','steam','nitrogen only'],hint:'People breathe this gas out.',explain:'Plants use carbon dioxide during photosynthesis.'},
];
const battleQuestions = [
  {subject:'mathematics',q:'A trainer has 4 groups of 6 crystals. How many crystals?',a:'24',opts:['10','20','24','28'],hint:'Multiply 4 by 6.',explain:'4 groups of 6 equals 24.'},
  {subject:'english',q:'Choose the sentence with correct punctuation.',a:'Mira said, “Follow the path.”',opts:['Mira said follow the path','Mira said, “Follow the path.”','mira said Follow the path','Mira said follow, the path.'],hint:'Look for a capital letter, comma and full stop.',explain:'Direct speech needs punctuation and quotation marks.'},
  {subject:'science',q:'Which is a living part of a forest ecosystem?',a:'tree',opts:['sunlight','water','tree','rock'],hint:'Living things grow and reproduce.',explain:'A tree is living; sunlight, water and rocks are non-living factors.'},
];

function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.floor(r.width*dpr));canvas.height=Math.max(1,Math.floor(r.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0)}
window.addEventListener('resize',resize);resize();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function round(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=5;ctx.stroke()}}
function character(x,y,body='#59a9e8',hair='#765234'){ctx.fillStyle=body;ctx.beginPath();ctx.arc(x,y,28,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f5c69d';ctx.beginPath();ctx.arc(x,y-30,19,0,Math.PI*2);ctx.fill();ctx.fillStyle=hair;ctx.beginPath();ctx.arc(x,y-37,19,Math.PI,Math.PI*2);ctx.fill()}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);const camX=clamp(player.x-w/2,0,1200-w),camY=clamp(player.y-h/2,0,1200-h);ctx.save();ctx.translate(-camX,-camY);ctx.fillStyle='#79d274';ctx.fillRect(0,0,1200,1200);ctx.fillStyle='#ecd48f';ctx.fillRect(70,720,1060,230);ctx.fillRect(585,140,240,940);for(let i=0;i<32;i++){const x=60+(i*173)%1080,y=80+(i*227)%1040;if(Math.abs(y-835)<145||Math.abs(x-705)<150)continue;ctx.fillStyle='#3f9752';ctx.beginPath();ctx.arc(x,y,28,0,Math.PI*2);ctx.fill();ctx.fillStyle='#795538';ctx.fillRect(x-6,y+20,12,38)}
round(incubator.x-120,incubator.y-90,240,180,22,'#e9e2ff','#fff');ctx.fillStyle='#8d72e8';ctx.fillRect(incubator.x-76,incubator.y-36,152,92);ctx.fillStyle='#bff6ff';ctx.beginPath();ctx.ellipse(incubator.x,incubator.y-35,52,62,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#17324d';ctx.font='900 18px Nunito';ctx.textAlign='center';ctx.fillText('INCUBATOR',incubator.x,incubator.y+125);
round(245,300,270,190,22,'#fff8df','#fff');ctx.fillStyle='#e66f82';ctx.beginPath();ctx.moveTo(225,300);ctx.lineTo(380,210);ctx.lineTo(535,300);ctx.closePath();ctx.fill();ctx.fillStyle='#17324d';ctx.fillText('Mira’s House',380,525);
round(900,780,190,150,22,'#fff8df','#fff');ctx.fillStyle='#ffca57';ctx.beginPath();ctx.moveTo(885,780);ctx.lineTo(995,710);ctx.lineTo(1105,780);ctx.closePath();ctx.fill();ctx.fillStyle='#17324d';ctx.fillText('TRAINER GARDEN',995,965);
character(mira.x,mira.y,'#73d8bd','#765234');ctx.fillStyle='#17324d';ctx.fillText('Mira',mira.x,mira.y-65);
character(trainer.x,trainer.y,'#ffca57','#4f3829');ctx.fillText('Trainer Sol',trainer.x,trainer.y-65);
character(player.x,player.y,'#59a9e8','#59422f');
if(state.stage==='carryEgg'){ctx.fillStyle=state.egg.shell;ctx.beginPath();ctx.ellipse(player.x+30,player.y-8,15,20,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke()}
if(state.creature){ctx.fillStyle=state.creature.isGold?'#e7b81d':'#8d72e8';ctx.beginPath();ctx.arc(player.x-50,player.y+12,25,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(player.x-58,player.y+4,5,0,Math.PI*2);ctx.arc(player.x-42,player.y+4,5,0,Math.PI*2);ctx.fill()}
ctx.restore()}
function updateHud(){stats.textContent=`Level ${state.level} · XP ${state.xp} · Coins ${state.coins} · ${state.creature?state.creature.nickname:'No companion yet'}`;objective.textContent=state.stage==='arrival'?'Mira is walking over to meet you…':state.stage==='meetMira'?'Talk with Mira.':state.stage==='carryEgg'?'Carry the egg to the nearby incubator.':state.stage==='hatching'?'Power the incubator with learning.':state.stage==='mission'?'Walk to Trainer Sol for your first mission battle.':state.stage==='complete'?'Demo complete — review the Parent and Teacher sections.':'Continue the adventure.'}
function update(dt){if(modal.classList.contains('open'))return;if(state.stage==='arrival'&&mira.walking){const dx=mira.targetX-mira.x,dy=mira.targetY-mira.y,l=Math.hypot(dx,dy);if(l>8){mira.x+=dx/l*120*dt;mira.y+=dy/l*120*dt}else{mira.walking=false;state.stage='meetMira';persist();setTimeout(showMiraIntro,200)}}const len=Math.hypot(move.x,move.y);if(len>.08&&state.stage!=='arrival'){player.x=clamp(player.x+move.x/Math.max(1,len)*player.speed*dt,40,1160);player.y=clamp(player.y+move.y/Math.max(1,len)*player.speed*dt,80,1160)}near=null;if(state.stage==='carryEgg'&&dist(player,incubator)<155)near={type:'incubator'};else if(state.stage==='meetMira'&&dist(player,mira)<130)near={type:'mira'};else if(state.stage==='mission'&&dist(player,trainer)<150)near={type:'trainer'};if(near){act.classList.add('ready');prompt.classList.add('show');prompt.textContent=near.type==='incubator'?'ACT: Use the incubator':near.type==='trainer'?'ACT: Challenge Trainer Sol':'ACT: Talk to Mira'}else{act.classList.remove('ready');prompt.classList.remove('show')}updateHud()}
function loop(ts){const dt=Math.min(.034,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop)}
requestAnimationFrame(loop);
function openModal(html){panel.innerHTML=html;modal.classList.add('open')}
function closeModal(){modal.classList.remove('open')}
function showMiraIntro(){openModal(`<h1>Mira</h1><p>Welcome to Verdara. I’m Mira, Keeper of Beginnings.</p><p>ASCEND is a creature-collecting school adventure across five countries. Your knowledge powers hatching, missions and battles. The game learns what you understand and where foundations need rebuilding.</p><p>I have your first egg. Carry it to the incubator nearby. You will customise the shell, then use learning energy to hatch the unknown monster inside.</p><div class="td-actions"><button class="td-btn primary" data-accept>ACCEPT THE EGG</button></div>`);panel.querySelector('[data-accept]').onclick=()=>{state.stage='carryEgg';persist();closeModal()}}
function eggHtml(){return `<div class="td-egg ${state.egg.pattern}" style="--shell:${state.egg.shell};--accent:${state.egg.accent}"></div>`}
function customiser(){openModal(`<h2>Incubator Shell Studio</h2><p>The shell design is yours. The species inside remains random until hatching.</p>${eggHtml()}<b>Affinity</b><div class="td-grid">${[['bloom','🌿 Bloom'],['starlight','✦ Starlight'],['tide','🌊 Tide']].map(([v,l])=>`<button class="td-option ${state.egg.familyId===v?'sel':''}" data-family="${v}">${l}</button>`).join('')}</div><b>Shell colour</b><div class="td-colours">${palette.map(c=>`<button class="td-colour ${state.egg.shell===c?'sel':''}" data-shell="${c}" style="background:${c}"></button>`).join('')}</div><b>Pattern colour</b><div class="td-colours">${palette.map(c=>`<button class="td-colour ${state.egg.accent===c?'sel':''}" data-accent="${c}" style="background:${c}"></button>`).join('')}</div><b>Pattern</b><div class="td-grid">${['spots','stars','waves'].map(v=>`<button class="td-option ${state.egg.pattern===v?'sel':''}" data-pattern="${v}">${v}</button>`).join('')}</div><label><b>Nickname</b><input class="td-input" maxlength="18" value="${state.egg.nickname}"></label><div class="td-actions"><button class="td-btn primary" data-start>START HATCHING</button></div>`);panel.querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>{state.egg.familyId=b.dataset.family;persist();customiser()});panel.querySelectorAll('[data-shell]').forEach(b=>b.onclick=()=>{state.egg.shell=b.dataset.shell;persist();customiser()});panel.querySelectorAll('[data-accent]').forEach(b=>b.onclick=()=>{state.egg.accent=b.dataset.accent;persist();customiser()});panel.querySelectorAll('[data-pattern]').forEach(b=>b.onclick=()=>{state.egg.pattern=b.dataset.pattern;persist();customiser()});panel.querySelector('.td-input').oninput=e=>{state.egg.nickname=e.target.value.slice(0,18);persist()};panel.querySelector('[data-start]').onclick=()=>{state.stage='hatching';hatchEnergy=0;questionIndex=0;persist();showHatchQuestion()}}
function record(q,correct){state.evidence.push({at:new Date().toISOString(),subject:q.subject,correct,context:state.stage});const change=correct?.04:-.015;state.subjectMastery[q.subject]=clamp((state.subjectMastery[q.subject]||.2)+change,0,1);persist()}
function showHatchQuestion(){const q=hatchQuestions[questionIndex%hatchQuestions.length],power=20+state.level*5;openModal(`<h2>Incubator Power</h2>${eggHtml()}<div class="td-meter"><span style="width:${hatchEnergy}%"></span></div><p>At Level ${state.level}, each correct answer creates <b>${power} hatch energy</b>.</p><div class="td-q">${q.q}</div><div class="td-answers">${q.opts.map(o=>`<button class="td-btn" data-answer="${o}">${o}</button>`).join('')}</div><div class="td-support"><button data-hint>💡 Hint</button><button data-explain>📖 Explain</button></div><div class="td-feedback"></div>`);panel.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const f=panel.querySelector('.td-feedback');if(b.dataset.answer!==q.a){record(q,false);f.textContent='Not yet. Use Hint or Explain, then try again.';return}record(q,true);hatchEnergy=Math.min(100,hatchEnergy+power);f.textContent=`Correct! +${power} hatch energy.`;setTimeout(()=>{if(hatchEnergy>=100)finishHatch();else{questionIndex++;showHatchQuestion()}},450)});panel.querySelector('[data-hint]').onclick=()=>panel.querySelector('.td-feedback').textContent=q.hint;panel.querySelector('[data-explain]').onclick=()=>panel.querySelector('.td-feedback').textContent=q.explain}
function finishHatch(){const creature=hatchCreature(state.egg.familyId);const species=getSpecies(creature.speciesId);creature.nickname=state.egg.nickname||species?.name||'Nova';state.creature=creature;state.activeCreatureUid=creature.uid;state.stage='mission';state.xp+=20;persist();openModal(`<h1>${creature.nickname} hatched!</h1><p><b>${species?.name||'Ascendant'}</b> · ${creature.rarity.toUpperCase()}</p><p>Every egg rolls from the 100-monster catalog using rarity-weighted hatch chances. Incubators are where future eggs are hatched and companions are changed.</p><p>Mira asks you to meet Trainer Sol for your first subject battle.</p><div class="td-actions"><button class="td-btn primary" data-go>LEAVE THE INCUBATOR</button></div>`);panel.querySelector('[data-go]').onclick=closeModal}
function battle(){battleHp=100;questionIndex=0;showBattleQuestion()}
function showBattleQuestion(){const q=battleQuestions[questionIndex%battleQuestions.length];const damage=20+state.level*8;openModal(`<h2>Trainer Battle</h2><p>${state.creature?.nickname||'Your companion'} vs Trainer Sol’s Spriglet</p><div class="td-meter"><span style="width:${battleHp}%"></span></div><p>Correct answers deal <b>${damage} damage</b> at Level ${state.level}.</p><div class="td-q">${q.q}</div><div class="td-answers">${q.opts.map(o=>`<button class="td-btn" data-answer="${o}">${o}</button>`).join('')}</div><div class="td-support"><button data-hint>💡 Hint</button><button data-explain>📖 Explain</button></div><div class="td-feedback"></div>`);panel.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const f=panel.querySelector('.td-feedback');if(b.dataset.answer!==q.a){record(q,false);f.textContent='The opponent blocks. Read the explanation and try again.';return}record(q,true);battleHp=Math.max(0,battleHp-damage);f.textContent=`Correct! ${damage} damage.`;setTimeout(()=>{if(battleHp<=0)winBattle();else{questionIndex++;showBattleQuestion()}},450)});panel.querySelector('[data-hint]').onclick=()=>panel.querySelector('.td-feedback').textContent=q.hint;panel.querySelector('[data-explain]').onclick=()=>panel.querySelector('.td-feedback').textContent=q.explain}
function winBattle(){state.stage='complete';state.missionComplete=true;state.level=2;state.xp+=80;state.coins+=50;state.eggs.push({id:`verdara-${Date.now()}`,familyId:'bloom',rarityHint:'unknown'});persist();openModal(`<h1>Mission complete!</h1><p>You defeated Trainer Sol and earned a new Verdara egg.</p><p>The complete loop demonstrated: NPC story → egg → incubator → adaptive hatching → random monster → exploration → trainer battle → egg reward → live learning report.</p><div class="td-actions"><button class="td-btn gold" data-report>OPEN PARENT REPORT</button><button class="td-btn primary" data-close>RETURN TO TOWN</button></div>`);panel.querySelector('[data-report]').onclick=showParentReport;panel.querySelector('[data-close]').onclick=closeModal}
function interact(){if(near?.type==='mira')showMiraIntro();else if(near?.type==='incubator')customiser();else if(near?.type==='trainer')battle();else{prompt.textContent='Move closer to the highlighted person or building.';prompt.classList.add('show');setTimeout(()=>{if(!near)prompt.classList.remove('show')},900)}}
function bindStick(){let active=false,id=null;const set=e=>{const r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=r.width*.29,l=Math.hypot(dx,dy)||1,s=Math.min(1,max/l);dx*=s;dy*=s;knob.style.transform=`translate(${dx}px,${dy}px)`;move={x:dx/max,y:dy/max}};stick.addEventListener('pointerdown',e=>{e.preventDefault();active=true;id=e.pointerId;stick.setPointerCapture(id);set(e)});stick.addEventListener('pointermove',e=>{if(active&&e.pointerId===id){e.preventDefault();set(e)}});const end=e=>{if(e.pointerId!==id)return;active=false;move={x:0,y:0};knob.style.transform='translate(0,0)'};stick.addEventListener('pointerup',end);stick.addEventListener('pointercancel',end)}
bindStick();act.addEventListener('pointerdown',e=>{e.preventDefault();interact()});
function reportGrade(value){if(value>=.85)return'A';if(value>=.7)return'B';if(value>=.55)return'C';if(value>=.4)return'D';return'E'}
function showParentReport(){const attempts=state.evidence.length,correct=state.evidence.filter(e=>e.correct).length,accuracy=attempts?Math.round(correct/attempts*100):0;openModal(`<h1>Live Parent Report</h1><p>This updates from demonstrated activity and is not an official school grade.</p><table class="td-table"><tr><th>Measure</th><th>Current evidence</th></tr><tr><td>Level</td><td>${state.level}</td></tr><tr><td>Attempts</td><td>${attempts}</td></tr><tr><td>Accuracy</td><td>${accuracy}%</td></tr>${Object.entries(state.subjectMastery).map(([s,v])=>`<tr><td>${s}</td><td>${Math.round(v*100)}% · Band ${reportGrade(v)}</td></tr>`).join('')}<tr><td>Teacher target</td><td>${state.assignment?`${state.assignment.subject}: ${state.assignment.skill}`:'None set'}</td></tr></table><div class="td-actions"><button class="td-btn alt" data-back>CLOSE</button></div>`);panel.querySelector('[data-back]').onclick=closeModal}
function showTeacher(){openModal(`<h1>Teacher Workspace</h1><p>Add a current classroom target. The demo records it as the preferred content focus while retaining prerequisite support.</p><label><b>Subject</b><select class="td-input td-subject"><option>mathematics</option><option>english</option><option>science</option></select></label><label><b>Skill or topic</b><input class="td-input td-skill" placeholder="e.g. fractions, persuasive writing, ecosystems"></label><label><b>Instructions or homework</b><textarea class="td-input td-notes" rows="4" placeholder="Paste the task or teacher notes"></textarea></label><div class="td-actions"><button class="td-btn primary" data-save>SAVE LEARNING TARGET</button><button class="td-btn alt" data-back>CLOSE</button></div>`);panel.querySelector('[data-save]').onclick=()=>{const subject=panel.querySelector('.td-subject').value,skill=panel.querySelector('.td-skill').value.trim(),notes=panel.querySelector('.td-notes').value.trim();if(!skill)return;state.assignment={subject,skill,notes,createdAt:new Date().toISOString()};persist();showParentReport()};panel.querySelector('[data-back]').onclick=closeModal}
function showAdultHub(){openModal(`<h1>Adult Hub</h1><div class="td-actions"><button class="td-btn gold" data-parent>LIVE PARENT REPORT</button><button class="td-btn primary" data-teacher>TEACHER WORKSPACE</button><button class="td-btn alt" data-close>CLOSE</button></div>`);panel.querySelector('[data-parent]').onclick=showParentReport;panel.querySelector('[data-teacher]').onclick=showTeacher;panel.querySelector('[data-close]').onclick=closeModal}
game.querySelector('.td-adult').onclick=showAdultHub;game.querySelector('.td-reset').onclick=()=>{localStorage.removeItem(KEY);location.reload()};
window.addEventListener('keydown',e=>{if(['ArrowUp','w','W'].includes(e.key))move.y=-1;if(['ArrowDown','s','S'].includes(e.key))move.y=1;if(['ArrowLeft','a','A'].includes(e.key))move.x=-1;if(['ArrowRight','d','D'].includes(e.key))move.x=1;if(['e','E',' '].includes(e.key)){e.preventDefault();interact()}});window.addEventListener('keyup',e=>{if(['ArrowUp','ArrowDown','w','W','s','S'].includes(e.key))move.y=0;if(['ArrowLeft','ArrowRight','a','A','d','D'].includes(e.key))move.x=0});
updateHud();
